name: sky_bridge
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  atproto: ^0.13.3
  bluesky: ^0.18.8
  bluesky_text: ^0.7.2
  collection: ^1.19.1
  copy_with_extension: ^6.0.0
  crypto: ^3.0.6
  dart_frog: ^1.2.0
  dart_jsonwebtoken: ^2.14.2
  dcli_core: ^6.1.0
  dotenv: ^4.1.0
  html: ^0.15.5
  http: ^0.13.6
  image_compression: ^1.0.5
  intl: ^0.20.1
  json_annotation: ^4.8.0
  orm: ^5.2.1
  path: ^1.8.3
  shelf_cors_headers: ^0.1.5
  shelf_rate_limiter: ^1.0.1
  template_expressions: ^3.0.0+5
  yet_another_json_isolate: ^2.0.3

dev_dependencies:
  build_runner: ^2.4.13
  copy_with_extension_gen: ^6.0.0
  fixnum: ^1.1.0
  # isar_generator: ^3.1.0+1
  json_serializable: ^6.9.0
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^7.0.0

dependency_overrides:
  http: ^0.13.6